/**
 *
 *  @file StoredResponse.hpp
 *  @author Softadastra
 *
 *  Copyright 2026, Softadastra.
 *  All rights reserved.
 *  https://github.com/softadastra/cnerium.git
 *
 *  Licensed under the MIT License.
 *
 *  Cnerium
 *
 */

#ifndef CNERIUM_STORE_STORED_RESPONSE_HPP
#define CNERIUM_STORE_STORED_RESPONSE_HPP

#include <string>
#include <string_view>

#include <cnerium/support/Json.hpp>

namespace cnerium::store
{
  /**
   * @brief Persisted HTTP response used by Cnerium idempotency.
   *
   * StoredResponse stores the response generated by a durable route so Cnerium
   * can return the same response when the same Idempotency-Key is received
   * again with the same request hash.
   */
  class StoredResponse
  {
  public:
    /**
     * @brief Creates an empty stored response.
     */
    StoredResponse() = default;

    /**
     * @brief Creates a stored response.
     *
     * @param status_code HTTP status code.
     * @param body Response body.
     * @param content_type Response content type.
     */
    StoredResponse(
        int status_code,
        std::string body,
        std::string content_type = "application/json; charset=utf-8");

    /**
     * @brief Creates a JSON stored response.
     *
     * @param status_code HTTP status code.
     * @param body JSON response body.
     * @return Stored response.
     */
    [[nodiscard]] static StoredResponse json(
        int status_code,
        const support::Json &body);

    /**
     * @brief Creates a text stored response.
     *
     * @param status_code HTTP status code.
     * @param body Text response body.
     * @return Stored response.
     */
    [[nodiscard]] static StoredResponse text(
        int status_code,
        std::string body);

    /**
     * @brief Restores a stored response from serialized JSON text.
     *
     * @param text Serialized stored response.
     * @return Stored response.
     *
     * @throws nlohmann::json::parse_error if the text is invalid JSON.
     */
    [[nodiscard]] static StoredResponse from_json_text(std::string_view text);

    /**
     * @brief Restores a stored response from a JSON object.
     *
     * @param value JSON object.
     * @return Stored response.
     */
    [[nodiscard]] static StoredResponse from_json(const support::Json &value);

    /**
     * @brief Returns the HTTP status code.
     *
     * @return HTTP status code.
     */
    [[nodiscard]] int status_code() const noexcept;

    /**
     * @brief Returns the response body.
     *
     * @return Response body.
     */
    [[nodiscard]] const std::string &body() const noexcept;

    /**
     * @brief Returns the response content type.
     *
     * @return Content type.
     */
    [[nodiscard]] const std::string &content_type() const noexcept;

    /**
     * @brief Sets the HTTP status code.
     *
     * @param value HTTP status code.
     */
    void set_status_code(int value) noexcept;

    /**
     * @brief Sets the response body.
     *
     * @param value Response body.
     */
    void set_body(std::string value);

    /**
     * @brief Sets the response content type.
     *
     * @param value Content type.
     */
    void set_content_type(std::string value);

    /**
     * @brief Returns true if the stored response has a body.
     *
     * @return true if body is not empty.
     */
    [[nodiscard]] bool has_body() const noexcept;

    /**
     * @brief Returns true if the stored response has a content type.
     *
     * @return true if content type is not empty.
     */
    [[nodiscard]] bool has_content_type() const noexcept;

    /**
     * @brief Returns true if the stored response can be replayed.
     *
     * @return true if status code is valid.
     */
    [[nodiscard]] bool is_valid() const noexcept;

    /**
     * @brief Backward-compatible alias for is_valid().
     *
     * @return true if the stored response is valid.
     */
    [[nodiscard]] bool valid() const noexcept;

    /**
     * @brief Converts the stored response to JSON.
     *
     * @return JSON object.
     */
    [[nodiscard]] support::Json to_json() const;

    /**
     * @brief Serializes the stored response to compact JSON text.
     *
     * @return JSON text.
     */
    [[nodiscard]] std::string to_json_text() const;

    /**
     * @brief Clears the stored response.
     */
    void clear() noexcept;

  private:
    int status_code_{200};
    std::string body_{};
    std::string content_type_{"application/json; charset=utf-8"};
  };

} // namespace cnerium::store

#endif // CNERIUM_STORE_STORED_RESPONSE_HPP
