/**
 *
 *  @file Idempotency.hpp
 *  @author Softadastra
 *
 *  Copyright 2026, Softadastra.
 *  All rights reserved.
 *  https://github.com/softadastra/cnerium.git
 *
 *  Licensed under the MIT License.
 *
 *  Cnerium
 *
 */

#ifndef CNERIUM_RELIABILITY_IDEMPOTENCY_HPP
#define CNERIUM_RELIABILITY_IDEMPOTENCY_HPP

#include <string_view>

#include <cnerium/reliability/DurableResult.hpp>
#include <cnerium/reliability/IdempotencyKey.hpp>
#include <cnerium/reliability/ReplayProtection.hpp>
#include <cnerium/reliability/RequestHash.hpp>
#include <cnerium/store/Store.hpp>
#include <cnerium/store/StoredResponse.hpp>

namespace cnerium::reliability
{
  /**
   * @brief High-level idempotency service for durable Cnerium routes.
   *
   * Idempotency coordinates request hashing, replay protection, and response
   * persistence for durable route handlers.
   *
   * It is intentionally small and depends only on the Cnerium Store facade,
   * which itself uses the public Softadastra SDK client.
   */
  class Idempotency
  {
  public:
    /**
     * @brief Creates an idempotency service using a Cnerium store.
     *
     * @param store Store used to persist hashes and responses.
     */
    explicit Idempotency(store::Store &store) noexcept;

    Idempotency(const Idempotency &) = delete;
    Idempotency &operator=(const Idempotency &) = delete;

    Idempotency(Idempotency &&) noexcept = delete;
    Idempotency &operator=(Idempotency &&) noexcept = delete;

    /**
     * @brief Checks whether a durable request should execute, replay, or fail.
     *
     * @param operation Durable operation name.
     * @param key Idempotency key.
     * @param body Request body.
     * @return Durable result selected by the reliability layer.
     */
    [[nodiscard]] DurableResult check(
        std::string_view operation,
        const IdempotencyKey &key,
        std::string_view body);

    /**
     * @brief Checks whether a durable request should execute, replay, or fail.
     *
     * @param operation Durable operation name.
     * @param key Idempotency key.
     * @param hash Precomputed request hash.
     * @return Durable result selected by the reliability layer.
     */
    [[nodiscard]] DurableResult check_hash(
        std::string_view operation,
        const IdempotencyKey &key,
        const RequestHash &hash);

    /**
     * @brief Saves a completed durable response.
     *
     * @param operation Durable operation name.
     * @param key Idempotency key.
     * @param body Request body.
     * @param response Response generated by the user handler.
     * @return true if the response was committed.
     */
    [[nodiscard]] bool commit(
        std::string_view operation,
        const IdempotencyKey &key,
        std::string_view body,
        const store::StoredResponse &response);

    /**
     * @brief Saves a completed durable response.
     *
     * @param operation Durable operation name.
     * @param key Idempotency key.
     * @param hash Precomputed request hash.
     * @param response Response generated by the user handler.
     * @return true if the response was committed.
     */
    [[nodiscard]] bool commit_hash(
        std::string_view operation,
        const IdempotencyKey &key,
        const RequestHash &hash,
        const store::StoredResponse &response);

    /**
     * @brief Computes the stable request hash used by Cnerium.
     *
     * @param body Request body.
     * @return Request hash.
     */
    [[nodiscard]] static RequestHash hash_body(std::string_view body);

  private:
    ReplayProtection replay_;
  };

} // namespace cnerium::reliability

#endif // CNERIUM_RELIABILITY_IDEMPOTENCY_HPP
